apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#Web API Prod Environment

bases:
- ../../bases
- ../../../../global/tnsnames/
- ../../../../global/env_var/prod/

 

namespace: webapi-prod

#nameSuffix: -prod
